### ISSUE TITLE
Allow setting additional caller depth

### ISSUE THREAD

**Issue by aphistic** [go-nacelle/log#1]
I have a wrapper that wraps the nacelle logger in a library to allow more than just nacelle to be used as a logger but the caller code looks like it assumes a certain depth, so the caller we see in the logs ends up being `state/logger.go:37` instead of the actual call site. It would be nice to be able to configure a logger (based on the default logger, similar to how `WithFields` would work) to add additional depth in cases such as this one.

**Comment by efritz** [comment]
Implemented in #2.
